version: 0.0
os: linux
files:
  - source: index.html
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: scripts/remove_old_index.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/reload_nginx.sh
      timeout: 60
      runas: root
